------------------------
----Kaizen#1769----
------------------------
ESX              = nil
local PlayerData = {}

Citizen.CreateThread(function()
    while ESX == nil do
        TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
        Citizen.Wait(0)
    end
end)

RegisterNetEvent('esx:playerLoaded')
AddEventHandler('esx:playerLoaded', function(xPlayer)
    PlayerData = xPlayer
end)

TriggerEvent('esx:getSharedObject', function(obj)
	ESX = obj
end)

--Xenons
RegisterNetEvent('kaizen_xenon:onColorA')
AddEventHandler('kaizen_xenon:onColorA', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 1)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorB')
AddEventHandler('kaizen_xenon:onColorB', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 2)
  Citizen.Wait(5200)------------------------
----Kaizen#1769----
------------------------
ESX              = nil
local PlayerData = {}

Citizen.CreateThread(function()
    while ESX == nil do
        TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
        Citizen.Wait(0)
    end
end)

RegisterNetEvent('esx:playerLoaded')
AddEventHandler('esx:playerLoaded', function(xPlayer)
    PlayerData = xPlayer
end)

TriggerEvent('esx:getSharedObject', function(obj)
	ESX = obj
end)

--Xenons
RegisterNetEvent('kaizen_xenon:onColorA')
AddEventHandler('kaizen_xenon:onColorA', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 1)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorB')
AddEventHandler('kaizen_xenon:onColorB', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 2)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorC')
AddEventHandler('kaizen_xenon:onColorC', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 3)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorD')
AddEventHandler('kaizen_xenon:onColorD', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 4)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorE')
AddEventHandler('kaizen_xenon:onColorE', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 5)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorF')
AddEventHandler('kaizen_xenon:onColorF', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 6)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorG')
AddEventHandler('kaizen_xenon:onColorG', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 7)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorH')
AddEventHandler('kaizen_xenon:onColorH', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 8)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorI')
AddEventHandler('kaizen_xenon:onColorI', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 9)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorJ')
AddEventHandler('kaizen_xenon:onColorJ', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 10)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorK')
AddEventHandler('kaizen_xenon:onColorK', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 11)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorL')
AddEventHandler('kaizen_xenon:onColorL', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 12)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorM')
AddEventHandler('kaizen_xenon:onColorM', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 13)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorN')
AddEventHandler('kaizen_xenon:onColorN', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 0)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

--Turbo
RegisterNetEvent('kaizen_turbo:turboN')
AddEventHandler('kaizen_turbo:turboN', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(10000, 'Retrait')
  ToggleVehicleMod(playerVeh, 18, false)
  Citizen.Wait(10200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_turbo:turboY')
AddEventHandler('kaizen_turbo:turboY', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(10000, 'Installation')
  ToggleVehicleMod(playerVeh, 18, true)
  Citizen.Wait(10200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

--Moteur
RegisterNetEvent('kaizen_engine:engine1')
AddEventHandler('kaizen_engine:engine1', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(20000, 'Installation')
  SetVehicleMod(playerVeh, 11, -1, true)
  Citizen.Wait(20200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_engine:engine2')
AddEventHandler('kaizen_engine:engine2', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(20000, 'Installation')
  SetVehicleMod(playerVeh, 11, 0, true)
  Citizen.Wait(20200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_engine:engine3')
AddEventHandler('kaizen_engine:engine3', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(20000, 'Installation')
  SetVehicleMod(playerVeh, 11, 1, true)
  Citizen.Wait(20200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_engine:engine4')
AddEventHandler('kaizen_engine:engine4', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(20000, 'Installation')
  SetVehicleMod(playerVeh, 11, 2, true)
  Citizen.Wait(20200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_engine:engine5')
AddEventHandler('kaizen_engine:engine5', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(20000, 'Installation')
  SetVehicleMod(playerVeh, 11, 3, true)
  Citizen.Wait(20200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

--Brakes
RegisterNetEvent('kaizen_brakes:brakes1')
AddEventHandler('kaizen_brakes:brakes1', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 12, -1, true)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_brakes:brakes2')
AddEventHandler('kaizen_brakes:brakes2', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 12, 0, true)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_brakes:brakes3')
AddEventHandler('kaizen_brakes:brakes3', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 12, 1, true)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_brakes:brakes4')
AddEventHandler('kaizen_brakes:brakes4', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 12, 2, true)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

--Transmission
RegisterNetEvent('kaizen_trans:trans1')
AddEventHandler('kaizen_trans:trans1', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 13, -1, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_trans:trans2')
AddEventHandler('kaizen_trans:trans2', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 13, 0, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_trans:trans3')
AddEventHandler('kaizen_trans:trans3', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 13, 1, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_trans:trans4')
AddEventHandler('kaizen_trans:trans4', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 13, 2, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

--Suspension
RegisterNetEvent('kaizen_susp:susp1')
AddEventHandler('kaizen_susp:susp1', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 15, -1, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_susp:susp2')
AddEventHandler('kaizen_susp:susp2', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 15, 0, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_susp:susp3')
AddEventHandler('kaizen_susp:susp3', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 15, 1, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_susp:susp4')
AddEventHandler('kaizen_susp:susp4', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 15, 2, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_susp:susp5')
AddEventHandler('kaizen_susp:susp5', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 15, 3, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

--Blindage
RegisterNetEvent('kaizen_arm:arm1')
AddEventHandler('kaizen_arm:arm1', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 16, -1, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_arm:arm2')
AddEventHandler('kaizen_arm:arm2', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 16, 0, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_arm:arm3')
AddEventHandler('kaizen_arm:arm3', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 16, 1, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_arm:arm4')
AddEventHandler('kaizen_arm:arm4', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 16, 2, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_arm:arm5')
AddEventHandler('kaizen_arm:arm5', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 16, 3, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

RegisterNetEvent('kaizen_arm:arm6')
AddEventHandler('kaizen_arm:arm6', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(9000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 16, 4, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
  ExecuteCommand( "lowercar")
end)

--Window Tint
RegisterNetEvent('kaizen_win:win1')
AddEventHandler('kaizen_win:win1', function()
  local playerVeh = GetPlayersLastVehicle()
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_MAID_CLEAN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 46, true)
  SetVehicleWindowTint(playerVeh, -1)
  Citizen.Wait(5200)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_win:win2')
AddEventHandler('kaizen_win:win2', function()
  local playerVeh = GetPlayersLastVehicle()
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_MAID_CLEAN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 46, true)
  SetVehicleWindowTint(playerVeh, 0)
  Citizen.Wait(5200)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_win:win3')
AddEventHandler('kaizen_win:win3', function()
  local playerVeh = GetPlayersLastVehicle()
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_MAID_CLEAN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 46, true)
  SetVehicleWindowTint(playerVeh, 1)
  Citizen.Wait(5200)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_win:win4')
AddEventHandler('kaizen_win:win4', function()
  local playerVeh = GetPlayersLastVehicle()
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_MAID_CLEAN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 46, true)
  SetVehicleWindowTint(playerVeh, 2)
  Citizen.Wait(5200)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_lift:win4')
AddEventHandler('kaizen_lift:win4', function()
  local playerVeh = GetPlayersLastVehicle()
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_MAID_CLEAN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 46, true)
  SetVehicleWindowTint(playerVeh, 2)
  Citizen.Wait(5200)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_mods:saveMods')
AddEventHandler('kaizen_mods:saveMods', function()
	local vehicle = GetVehiclePedIsIn(PlayerPedId(), false)
	myCar = ESX.Game.GetVehicleProperties(vehicle)
	TriggerServerEvent('kaizen_mods:refreshOwnedVehicle', myCar)
end)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorC')
AddEventHandler('kaizen_xenon:onColorC', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 3)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorD')
AddEventHandler('kaizen_xenon:onColorD', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 4)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorE')
AddEventHandler('kaizen_xenon:onColorE', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 5)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorF')
AddEventHandler('kaizen_xenon:onColorF', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 6)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorG')
AddEventHandler('kaizen_xenon:onColorG', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 7)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorH')
AddEventHandler('kaizen_xenon:onColorH', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 8)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorI')
AddEventHandler('kaizen_xenon:onColorI', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 9)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorJ')
AddEventHandler('kaizen_xenon:onColorJ', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 10)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorK')
AddEventHandler('kaizen_xenon:onColorK', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 11)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorL')
AddEventHandler('kaizen_xenon:onColorL', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 12)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorM')
AddEventHandler('kaizen_xenon:onColorM', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 13)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_xenon:onColorN')
AddEventHandler('kaizen_xenon:onColorN', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 22, true)
  SetVehicleXenonLightsColour(playerVeh, 0)
  Citizen.Wait(5200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

--Turbo
RegisterNetEvent('kaizen_turbo:turboN')
AddEventHandler('kaizen_turbo:turboN', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(10000, 'Retrait')
  ToggleVehicleMod(playerVeh, 18, false)
  Citizen.Wait(10200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_turbo:turboY')
AddEventHandler('kaizen_turbo:turboY', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(10000, 'Installation')
  ToggleVehicleMod(playerVeh, 18, true)
  Citizen.Wait(10200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

--Moteur
RegisterNetEvent('kaizen_engine:engine1')
AddEventHandler('kaizen_engine:engine1', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(20000, 'Installation')
  SetVehicleMod(playerVeh, 11, -1, true)
  Citizen.Wait(20200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_engine:engine2')
AddEventHandler('kaizen_engine:engine2', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(20000, 'Installation')
  SetVehicleMod(playerVeh, 11, 0, true)
  Citizen.Wait(20200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_engine:engine3')
AddEventHandler('kaizen_engine:engine3', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(20000, 'Installation')
  SetVehicleMod(playerVeh, 11, 1, true)
  Citizen.Wait(20200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_engine:engine4')
AddEventHandler('kaizen_engine:engine4', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(20000, 'Installation')
  SetVehicleMod(playerVeh, 11, 2, true)
  Citizen.Wait(20200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_engine:engine5')
AddEventHandler('kaizen_engine:engine5', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(20000, 'Installation')
  SetVehicleMod(playerVeh, 11, 3, true)
  Citizen.Wait(20200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

--Brakes
RegisterNetEvent('kaizen_brakes:brakes1')
AddEventHandler('kaizen_brakes:brakes1', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 12, -1, true)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_brakes:brakes2')
AddEventHandler('kaizen_brakes:brakes2', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 12, 0, true)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_brakes:brakes3')
AddEventHandler('kaizen_brakes:brakes3', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 12, 1, true)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_brakes:brakes4')
AddEventHandler('kaizen_brakes:brakes4', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 12, 2, true)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

--Transmission
RegisterNetEvent('kaizen_trans:trans1')
AddEventHandler('kaizen_trans:trans1', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 13, -1, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_trans:trans2')
AddEventHandler('kaizen_trans:trans2', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 13, 0, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_trans:trans3')
AddEventHandler('kaizen_trans:trans3', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 13, 1, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_trans:trans4')
AddEventHandler('kaizen_trans:trans4', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 13, 2, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

--Suspension
RegisterNetEvent('kaizen_susp:susp1')
AddEventHandler('kaizen_susp:susp1', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 15, -1, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_susp:susp2')
AddEventHandler('kaizen_susp:susp2', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 15, 0, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_susp:susp3')
AddEventHandler('kaizen_susp:susp3', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 15, 1, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_susp:susp4')
AddEventHandler('kaizen_susp:susp4', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 15, 2, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_susp:susp5')
AddEventHandler('kaizen_susp:susp5', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 15, 3, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

--Blindage
RegisterNetEvent('kaizen_arm:arm1')
AddEventHandler('kaizen_arm:arm1', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 16, -1, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_arm:arm2')
AddEventHandler('kaizen_arm:arm2', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 16, 0, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_arm:arm3')
AddEventHandler('kaizen_arm:arm3', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 16, 1, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_arm:arm4')
AddEventHandler('kaizen_arm:arm4', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 16, 2, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_arm:arm5')
AddEventHandler('kaizen_arm:arm5', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 16, 3, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_arm:arm6')
AddEventHandler('kaizen_arm:arm6', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  exports['progressBars']:startUI(15000, 'Installation')
  SetVehicleMod(playerVeh, 16, 4, true)
  Citizen.Wait(15200)
  SetVehicleDoorShut(playerVeh, 4, false)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

--Window Tint
RegisterNetEvent('kaizen_win:win1')
AddEventHandler('kaizen_win:win1', function()
  local playerVeh = GetPlayersLastVehicle()
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_MAID_CLEAN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 46, true)
  SetVehicleWindowTint(playerVeh, -1)
  Citizen.Wait(5200)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_win:win2')
AddEventHandler('kaizen_win:win2', function()
  local playerVeh = GetPlayersLastVehicle()
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_MAID_CLEAN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 46, true)
  SetVehicleWindowTint(playerVeh, 0)
  Citizen.Wait(5200)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_win:win3')
AddEventHandler('kaizen_win:win3', function()
  local playerVeh = GetPlayersLastVehicle()
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_MAID_CLEAN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 46, true)
  SetVehicleWindowTint(playerVeh, 1)
  Citizen.Wait(5200)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_win:win4')
AddEventHandler('kaizen_win:win4', function()
  local playerVeh = GetPlayersLastVehicle()
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_MAID_CLEAN', 0, true)
  exports['progressBars']:startUI(5000, 'Installation')
  ToggleVehicleMod(playerVeh, 46, true)
  SetVehicleWindowTint(playerVeh, 2)
  Citizen.Wait(5200)
  ClearPedTasksImmediately(GetPlayerPed(-1))
end)

RegisterNetEvent('kaizen_mods:saveMods')
AddEventHandler('kaizen_mods:saveMods', function()
	local vehicle = GetVehiclePedIsIn(PlayerPedId(), false)
	myCar = ESX.Game.GetVehicleProperties(vehicle)
	TriggerServerEvent('kaizen_mods:refreshOwnedVehicle', myCar)
end)
