INSERT INTO items (`name`,`label`,`weight`,`rare`,`can_remove`) VALUES
('xenonsbleu', 'Blue Xenons', 0, 0, 1),
('xenonsbleuelect', 'Electric Blue Xenons', 0, 0, 1),
('xenonsmenthe', 'Mint Xenons', 0, 0, 1),
('xenonsvert', 'Green Xenons', 0, 0, 1),
('xenonsjaune', 'Yellow Xenons', 0, 0, 1),
('xenonsgold', 'Gold Xenons', 0, 0, 1),
('xenonsorange', 'Orange Xenons', 0, 0, 1),
('xenonsrouge', 'Red Xenons', 0, 0, 1),
('xenonsrose', 'Pink Xenons', 0, 0, 1),
('xenonsrose2', 'Hot Pink Xenons', 0, 0, 1),
('xenonsmauve', 'Purple Xenone', 0, 0, 1),
('xenonsblacklight', 'Blacklight Xenons', 0, 0, 1),
('xenonsdefault', 'White Xenons', 0, 0, 1),
('turboN', 'Remove Turbo Kit', 0, 0, 1),
('turbo', 'Turbo Kit', 0, 0, 1),
('engine1', 'Original Engine', 0, 0, 1),
('engine2', 'Engine Lvl. 1', 0, 0, 1),
('engine3', 'Engine Lvl. 2', 0, 0, 1),
('engine4', 'Engine Lvl. 3', 0, 0, 1),
('engine5', 'Engine Lvl. 4', 0, 0, 1),
('brakes1', 'Original Brakes', 0, 0, 1),
('brakes2', 'Brakes Lvl. 1', 0, 0, 1),
('brakes3', 'Brakes Lvl. 2', 0, 0, 1),
('brakes4', 'Brakes Lvl. 3', 0, 0, 1),
('trans1', 'Original Transmission', 0, 0, 1),
('trans2', 'Transmission Lvl. 1', 0, 0, 1),
('trans3', 'Transmission Lvl. 2', 0, 0, 1),
('trans4', 'Transmission Lvl. 3', 0, 0, 1),
('susp1', 'Original Suspension', 0, 0, 1),
('susp2', 'Suspension Lvl. 1', 0, 0, 1),
('susp3', 'Suspension Lvl. 2', 0, 0, 1),
('susp4', 'Suspension Lvl. 3', 0, 0, 1),
('susp5', 'Suspension Lvl. 4', 0, 0, 1),
('arm1', 'Remove Armor', 0, 0, 1),
('arm2', 'Armor Lvl. 1', 0, 0, 1),
('arm3', 'Armor Lvl. 2', 0, 0, 1),
('arm4', 'Armor Lvl. 3', 0, 0, 1),
('arm5', 'Armor Lvl. 4', 0, 0, 1),
('arm6', 'Armor Lvl. 5', 0, 0, 1),
('win1', 'Remove Window Tint', 0, 0, 1),
('win2', 'Light Smoke Window Tint', 0, 0, 1),
('win3', 'Dark Smoke Window Tint', 0, 0, 1),
('win4', 'Limo Window Tint', 0, 0, 1);
