------------------------
----Kaizen#1769----
------------------------

INSERT INTO items (`name`,`label`,`weight`,`rare`,`can_remove`) VALUES
('xenonsbleu', 'Xenons Bleues', 0, 0, 1),
('xenonsbleuelect', 'Xenons Bleue Electriques', 0, 0, 1),
('xenonsmenthe', 'Xenons Menthe', 0, 0, 1),
('xenonsvert', 'Xenons Verts', 0, 0, 1),
('xenonsjaune', 'Xenons Jaunes', 0, 0, 1),
('xenonsgold', 'Xenons Golds', 0, 0, 1),
('xenonsorange', 'Xenons Oranges', 0, 0, 1),
('xenonsrouge', 'Xenons Rouges', 0, 0, 1),
('xenonsrose', 'Xenons Roses', 0, 0, 1),
('xenonsrose2', 'Xenons Roses 2', 0, 0, 1),
('xenonsmauve', 'Xenons Mauves', 0, 0, 1),
('xenonsblacklight', 'Xenons Blacklight', 0, 0, 1),
('xenonsdefault', 'Xenons Default', 0, 0, 1),
('turboN', 'Turbo D\'Origine', 0, 0, 1),
('turbo', 'Kit Turbo', 0, 0, 1),
('engine1', 'Moteur D\'Origine', 0, 0, 1),
('engine2', 'Moteur Niv. 1', 0, 0, 1),
('engine3', 'Moteur Niv. 2', 0, 0, 1),
('engine4', 'Moteur Niv. 3', 0, 0, 1),
('engine5', 'Moteur Niv. 4', 0, 0, 1);
('brakes1', 'Freins D\'Origine', 0, 0, 1),
('brakes2', 'Freins Niv. 1', 0, 0, 1),
('brakes3', 'Freins Niv. 2', 0, 0, 1),
('brakes4', 'Freins Niv. 3', 0, 0, 1),
('trans1', 'Transmission D\'Origine', 0, 0, 1),
('trans2', 'Transmission Niv. 1', 0, 0, 1),
('trans3', 'Transmission Niv. 2', 0, 0, 1),
('trans4', 'Transmission Niv. 3', 0, 0, 1),
('susp1', 'Suspension D\'Origine', 0, 0, 1),
('susp2', 'Suspension Niv. 1', 0, 0, 1),
('susp3', 'Suspension Niv. 2', 0, 0, 1),
('susp4', 'Suspension Niv. 3', 0, 0, 1),
('susp5', 'Suspension Niv. 4', 0, 0, 1),
('arm1', 'Blindage D\'Origine', 0, 0, 1),
('arm2', 'Blindage Niv. 1', 0, 0, 1),
('arm3', 'Blindage Niv. 2', 0, 0, 1),
('arm4', 'Blindage Niv. 3', 0, 0, 1),
('arm5', 'Blindage Niv. 4', 0, 0, 1),
('arm6', 'Blindage Niv. 5', 0, 0, 1),
('win1', 'Vitre Teintées D\'Origine', 0, 0, 1),
('win2', 'Vitre Teintées Niv. 1', 0, 0, 1),
('win3', 'Vitre Teintées Niv. 2', 0, 0, 1),
('win4', 'Vitre Teintées Niv. 3', 0, 0, 1);